openapi: 3.0.3
info:
  title: Deep Research Agent API
  description: |
    Backend API for Deep Research Agent multi-agent workflow system.
    Supports WebSocket for real-time agent state updates and REST for query management.
  version: 1.0.0
  contact:
    name: Deep Research Agent Team

servers:
  - url: http://localhost:8000
    description: Local development server

tags:
  - name: Thread Management
    description: Conversation thread operations
  - name: Query Management
    description: Research query operations
  - name: WebSocket
    description: Real-time communication

paths:
  /threads:
    post:
      tags:
        - Thread Management
      summary: Create new conversation thread
      description: Creates a new conversation thread for multi-turn dialogue
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                session_id:
                  type: string
                  description: Browser session identifier
              required:
                - session_id
      responses:
        '201':
          description: Thread created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConversationThread'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /threads/{thread_id}:
    get:
      tags:
        - Thread Management
      summary: Get thread details
      description: Retrieves conversation thread with all queries and answers
      parameters:
        - name: thread_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Thread details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConversationThreadDetail'
        '404':
          description: Thread not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    delete:
      tags:
        - Thread Management
      summary: Close thread
      description: Closes conversation thread and cleans up resources
      parameters:
        - name: thread_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: Thread closed successfully
        '404':
          description: Thread not found

  /threads/{thread_id}/queries:
    post:
      tags:
        - Query Management
      summary: Submit research query
      description: |
        Submits a new research query to the thread. This initiates the multi-agent workflow.
        Real-time updates are sent via WebSocket connection.
      parameters:
        - name: thread_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                content:
                  type: string
                  minLength: 1
                  maxLength: 2000
                  description: Research question text
                  example: "quantum computing의 최신 발전 동향은?"
                search_sources:
                  type: array
                  items:
                    type: string
                    enum: [google, arxiv]
                  minItems: 1
                  description: Search sources to use
                  example: ["google", "arxiv"]
              required:
                - content
                - search_sources
      responses:
        '202':
          description: Query accepted and processing started
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResearchQuery'
        '400':
          description: Invalid query
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Thread not found

  /queries/{query_id}:
    get:
      tags:
        - Query Management
      summary: Get query status
      description: Retrieves current status and results of a research query
      parameters:
        - name: query_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Query details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QueryDetail'
        '404':
          description: Query not found

  /queries/{query_id}/answer:
    get:
      tags:
        - Query Management
      summary: Get synthesized answer
      description: Retrieves the final synthesized answer for a completed query
      parameters:
        - name: query_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Synthesized answer
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SynthesizedAnswer'
        '404':
          description: Answer not found
        '425':
          description: Answer not ready yet (query still processing)

  /ws/{thread_id}:
    get:
      tags:
        - WebSocket
      summary: WebSocket connection for real-time updates
      description: |
        Establishes WebSocket connection for receiving real-time agent state updates.
        
        **Message Types**:
        - `agent_state_update`: Agent status/progress changed
        - `agent_message`: Inter-agent communication event
        - `query_status_update`: Query status changed
        - `answer_ready`: Final answer is available
        - `error`: Error occurred
        
        See WebSocket Events schema for detailed message formats.
      parameters:
        - name: thread_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '101':
          description: Switching Protocols - WebSocket connection established

components:
  schemas:
    ConversationThread:
      type: object
      properties:
        id:
          type: string
          format: uuid
        session_id:
          type: string
        status:
          type: string
          enum: [active, idle, closed]
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
      required:
        - id
        - session_id
        - status
        - created_at
        - updated_at

    ConversationThreadDetail:
      allOf:
        - $ref: '#/components/schemas/ConversationThread'
        - type: object
          properties:
            queries:
              type: array
              items:
                $ref: '#/components/schemas/ResearchQuery'
            answers:
              type: array
              items:
                $ref: '#/components/schemas/SynthesizedAnswer'

    ResearchQuery:
      type: object
      properties:
        id:
          type: string
          format: uuid
        thread_id:
          type: string
          format: uuid
        content:
          type: string
          minLength: 1
          maxLength: 2000
        search_sources:
          type: array
          items:
            type: string
            enum: [google, arxiv]
        status:
          type: string
          enum: [pending, processing, completed, failed]
        created_at:
          type: string
          format: date-time
      required:
        - id
        - thread_id
        - content
        - search_sources
        - status
        - created_at

    QueryDetail:
      allOf:
        - $ref: '#/components/schemas/ResearchQuery'
        - type: object
          properties:
            agent_states:
              type: array
              items:
                $ref: '#/components/schemas/AgentState'
            search_results:
              type: array
              items:
                $ref: '#/components/schemas/SearchResult'
            research_plan:
              $ref: '#/components/schemas/ResearchPlan'

    AgentState:
      type: object
      properties:
        agent_id:
          type: string
          enum: [planning, research, reflect, content]
        query_id:
          type: string
          format: uuid
        status:
          type: string
          enum: [idle, thinking, working, completed, failed]
        progress:
          type: number
          format: float
          minimum: 0.0
          maximum: 1.0
        current_task:
          type: string
          nullable: true
        intermediate_result:
          type: object
          nullable: true
          description: Agent-specific intermediate results
        error:
          type: string
          nullable: true
        updated_at:
          type: string
          format: date-time
      required:
        - agent_id
        - query_id
        - status
        - progress
        - updated_at

    SearchResult:
      type: object
      properties:
        id:
          type: string
          format: uuid
        query_id:
          type: string
          format: uuid
        source:
          type: string
          enum: [google, arxiv]
        title:
          type: string
        url:
          type: string
          format: uri
        snippet:
          type: string
        authors:
          type: array
          items:
            type: string
          nullable: true
        published_date:
          type: string
          format: date-time
          nullable: true
        relevance_score:
          type: number
          format: float
          minimum: 0.0
          maximum: 1.0
          nullable: true
        created_at:
          type: string
          format: date-time
      required:
        - id
        - query_id
        - source
        - title
        - url
        - snippet
        - created_at

    ResearchPlan:
      type: object
      properties:
        id:
          type: string
          format: uuid
        query_id:
          type: string
          format: uuid
        strategy:
          type: string
        keywords:
          type: array
          items:
            type: string
        search_steps:
          type: array
          items:
            $ref: '#/components/schemas/SearchStep'
        estimated_time:
          type: integer
          description: Estimated time in seconds
        created_at:
          type: string
          format: date-time
      required:
        - id
        - query_id
        - strategy
        - keywords
        - search_steps
        - estimated_time
        - created_at

    SearchStep:
      type: object
      properties:
        step_number:
          type: integer
          minimum: 1
        description:
          type: string
        sources:
          type: array
          items:
            type: string
            enum: [google, arxiv]
        keywords:
          type: array
          items:
            type: string
      required:
        - step_number
        - description
        - sources
        - keywords

    SynthesizedAnswer:
      type: object
      properties:
        id:
          type: string
          format: uuid
        query_id:
          type: string
          format: uuid
        thread_id:
          type: string
          format: uuid
        content:
          type: string
          description: Answer in Markdown format
        sources:
          type: array
          items:
            $ref: '#/components/schemas/SourceCitation'
        sections:
          type: array
          items:
            $ref: '#/components/schemas/AnswerSection'
        metadata:
          $ref: '#/components/schemas/AnswerMetadata'
        created_at:
          type: string
          format: date-time
      required:
        - id
        - query_id
        - thread_id
        - content
        - sources
        - sections
        - metadata
        - created_at

    SourceCitation:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: References SearchResult ID
        title:
          type: string
        url:
          type: string
          format: uri
        citation_number:
          type: integer
          minimum: 1
      required:
        - id
        - title
        - url
        - citation_number

    AnswerSection:
      type: object
      properties:
        heading:
          type: string
        content:
          type: string
        citations:
          type: array
          items:
            type: integer
            minimum: 1
      required:
        - heading
        - content
        - citations

    AnswerMetadata:
      type: object
      properties:
        total_sources:
          type: integer
        google_sources:
          type: integer
        arxiv_sources:
          type: integer
        word_count:
          type: integer
      required:
        - total_sources
        - google_sources
        - arxiv_sources
        - word_count

    Error:
      type: object
      properties:
        error:
          type: string
        message:
          type: string
        details:
          type: object
          nullable: true
      required:
        - error
        - message

    # WebSocket Event Schemas
    AgentStateUpdateEvent:
      type: object
      properties:
        type:
          type: string
          enum: [agent_state_update]
        data:
          $ref: '#/components/schemas/AgentState'
      required:
        - type
        - data

    AgentMessageEvent:
      type: object
      properties:
        type:
          type: string
          enum: [agent_message]
        data:
          $ref: '#/components/schemas/AgentMessage'
      required:
        - type
        - data

    AgentMessage:
      type: object
      properties:
        id:
          type: string
          format: uuid
        query_id:
          type: string
          format: uuid
        sender:
          type: string
          enum: [planning, research, reflect, content]
        recipient:
          type: string
          enum: [planning, research, reflect, content]
          nullable: true
        message_type:
          type: string
          enum: [request, response, notification, error]
        content:
          type: object
          description: Message-type specific content
        timestamp:
          type: string
          format: date-time
      required:
        - id
        - query_id
        - sender
        - message_type
        - content
        - timestamp

    QueryStatusUpdateEvent:
      type: object
      properties:
        type:
          type: string
          enum: [query_status_update]
        data:
          type: object
          properties:
            query_id:
              type: string
              format: uuid
            status:
              type: string
              enum: [pending, processing, completed, failed]
            error:
              type: string
              nullable: true
          required:
            - query_id
            - status
      required:
        - type
        - data

    AnswerReadyEvent:
      type: object
      properties:
        type:
          type: string
          enum: [answer_ready]
        data:
          type: object
          properties:
            query_id:
              type: string
              format: uuid
            answer_id:
              type: string
              format: uuid
          required:
            - query_id
            - answer_id
      required:
        - type
        - data

    ErrorEvent:
      type: object
      properties:
        type:
          type: string
          enum: [error]
        data:
          $ref: '#/components/schemas/Error'
      required:
        - type
        - data
