"""Synthesized Answer model."""

from typing import List

from pydantic import BaseModel, Field, HttpUrl

from . import BaseEntity, UUID


class SourceCitation(BaseModel):
    """Represents a source citation in the answer."""
    
    id: UUID = Field(..., description="Source ID (references SearchResult ID)")
    title: str = Field(..., description="Source title")
    url: HttpUrl = Field(..., description="Source URL")
    citation_number: int = Field(..., ge=1, description="Citation number in text [1], [2], ...")
    
    class Config:
        json_schema_extra = {
            "example": {
                "id": "880e8400-e29b-41d4-a716-446655440003",
                "title": "Quantum Computing Breakthrough 2024",
                "url": "https://example.com/quantum-2024",
                "citation_number": 1
            }
        }


class AnswerSection(BaseModel):
    """Represents a section in the synthesized answer."""
    
    heading: str = Field(..., description="Section heading")
    content: str = Field(..., description="Section content")
    citations: List[int] = Field(default_factory=list, description="Citation numbers used in this section")
    
    class Config:
        json_schema_extra = {
            "example": {
                "heading": "개요",
                "content": "Quantum computing은 2024년 들어 획기적인 발전을 이루었습니다[1].",
                "citations": [1]
            }
        }


class AnswerMetadata(BaseModel):
    """Metadata about the synthesized answer."""
    
    total_sources: int = Field(..., ge=0, description="Total number of sources")
    google_sources: int = Field(..., ge=0, description="Number of Google search sources")
    arxiv_sources: int = Field(..., ge=0, description="Number of arXiv paper sources")
    word_count: int = Field(..., ge=0, description="Word count of the answer")
    
    class Config:
        json_schema_extra = {
            "example": {
                "total_sources": 2,
                "google_sources": 1,
                "arxiv_sources": 1,
                "word_count": 850
            }
        }


class SynthesizedAnswer(BaseEntity):
    """
    Represents the final answer generated by Content Writing Agent.
    
    Includes:
    - Structured content (Markdown format)
    - Source citations with proper numbering
    - Sections for organization
    - Metadata about sources and length
    """
    
    query_id: UUID = Field(..., description="ID of the related query")
    thread_id: UUID = Field(..., description="ID of the conversation thread")
    content: str = Field(..., description="Answer content in Markdown format")
    sources: List[SourceCitation] = Field(..., min_length=1, description="List of cited sources")
    sections: List[AnswerSection] = Field(..., min_length=1, description="Answer sections")
    metadata: AnswerMetadata = Field(..., description="Answer metadata")
    
    class Config:
        json_schema_extra = {
            "example": {
                "id": "770e8400-e29b-41d4-a716-446655440002",
                "query_id": "550e8400-e29b-41d4-a716-446655440000",
                "thread_id": "660e8400-e29b-41d4-a716-446655440001",
                "content": "# Quantum Computing의 최신 발전 동향\n\n## 개요\n...",
                "sources": [
                    {
                        "id": "880e8400-e29b-41d4-a716-446655440003",
                        "title": "Quantum Computing Breakthrough 2024",
                        "url": "https://example.com/quantum-2024",
                        "citation_number": 1
                    }
                ],
                "sections": [
                    {
                        "heading": "개요",
                        "content": "Quantum computing은 2024년 들어 획기적인 발전을 이루었습니다[1].",
                        "citations": [1]
                    }
                ],
                "metadata": {
                    "total_sources": 2,
                    "google_sources": 1,
                    "arxiv_sources": 1,
                    "word_count": 850
                },
                "created_at": "2025-11-14T10:31:00Z"
            }
        }
